### ISSUE TITLE
Default conf doesn't create a deb file

### ISSUE THREAD

**Issue by doom-fr** [thibDev/debpac#1]
when I open debpac, and push 'generate package' button, no file is produced.
If I change the package name it is the same.

I have also tried to add a file but there's nothing in the menu and dragging and dropping files produced anything also.

When I launch it with sudo, window does not open.

**Comment by ThiBsc** [comment]
@doom-fr, Have you the *gksu* package installed ? Because, without this package, you can't generate it.
If you don't use the released package at this [page](https://github.com/thibDev/debpac/releases), it's possibly the reason.

**Comment by ThiBsc** [comment]
I have fix an issue in my model, I have test your action with success. I mark as resolved
