### ISSUE TITLE
Remove gksu

### ISSUE THREAD

**Issue by JesusChapman** [thibDev/debpac#2]
Hello friend your app is facinanate, but there are two problems with it, 
1- I don't see the indicator for one to put the dependencies of the package. 

2- use Android and the termux app with xfce4, termux is a terminal emulator that does not require root, and your app asks for gksu, that package to run it on an android requires root, could you make a version that does not ask for gksu?, I would appreciate it 

![Screenshot_20210531-103533](https://user-images.githubusercontent.com/64093255/120216238-5eb87b80-c1fc-11eb-9dc9-dcd0b2543790.png)
![Screenshot_20210531-103514](https://user-images.githubusercontent.com/64093255/120216248-611ad580-c1fc-11eb-88a2-bd6a96bd3d84.png)

**Comment by ThiBsc** [comment]
@Yisus7u7 Hi, thank you for your feedback
For the first question, I'm not sure to understand, the dependencies of your package are just an information in your control file. In that case, nothing should appear in the tree view.

For the second question, yes I can take a look to give you the possibility to bypass gksu when I'll have the time

**Comment by JesusChapman** [comment]
Well thanks, I would appreciate it very much to remove gtksu, And also the Android paths to create deb packages is different from the one they should  And also the Android paths to create deb packages is different from that of debían, 

In debían is :  

/usr
/bin

On Android it is :

/data/data/com.termux/files/usr/bin
/data/data/com.termux/files/usr

And your app uses only the /bin and /usr path

**Comment by ThiBsc** [comment]
Ok for that part, you can add a define in the `.pro` file only for android environment

**Comment by JesusChapman** [comment]
![Screenshot_20210531-110629](https://user-images.githubusercontent.com/64093255/120219085-49dde700-c200-11eb-9988-c1aec721e373.png)

Which part should I edit?

**Comment by ThiBsc** [comment]
Is not the only things to do, and it depends of the Qt version you use to compile, maybe something like this to add:
```
android {
    DEFINES += USE_ANDROID_PATH
}
```
then, in the part of code to generate the package, if this define is here, do something

**Comment by JesusChapman** [comment]
The qt version of Android used is the latest, the 5, pd: I don't know how to program in c++

**Comment by JesusChapman** [comment]
But all the necessary dependencies of your Android project have them, a gksu expeción that requires root

**Comment by ThiBsc** [comment]
> The qt version of Android used is the latest, the 5, pd: I don't know how to program in c++

Ok, so just let me the time to see this. maybe this weekend but not sure ;)

**Comment by JesusChapman** [comment]
SIf you do not know the file system of the Android terminal you can consult:

https://github.com/termux/termux-packages/wiki/Termux-file-system-layout

**Comment by ThiBsc** [comment]
@Yisus7u7 I removed the gksu dependency (the package was removed from ubuntu). And I also add you the possibility to use define in .pro like this:
```txt
DEFINES += USE_TERMUX_PATH
```
Try to compile with it, and tell me if it solve your problem

**Comment by JesusChapman** [comment]
I'll try, thanks bro

**Comment by JesusChapman** [comment]
The termux route didn't work, and when building the package .deb gives me this error:

![Screenshot_20210602-133601](https://user-images.githubusercontent.com/64093255/120534754-d1b22580-c3a7-11eb-92b2-2fd1429840ee.png)
![Screenshot_20210602-133645](https://user-images.githubusercontent.com/64093255/120534764-d4147f80-c3a7-11eb-8e93-d6eeda0ded77.png)

**Comment by ThiBsc** [comment]
Have you cleaned your build folder before compiling with this define ?
Graphically, there is no difference, the difference it's in the debian package tree itself.

**Comment by JesusChapman** [comment]
Yes, clean the folder, it still has error

**Comment by ThiBsc** [comment]
I just try it on my config, it is working like a charm with this defines. It's difficult to debug something without your environment.
I tried in normal user and as sudo, both working, I need more informations, maybe you can add some qDebug() macro to the source file to try to understanding the problem.

**Comment by JesusChapman** [comment]
If you have a cell phone you can simply install the termux app and be able to test from there

**Comment by ThiBsc** [comment]
You have compiled my program on a cellphone ? Wooh, I don't know that it is working, I'll try when I'll have the time. When I generate a package with this defines on my ubuntu, the tree of the debian package look like:
```txt
|-DEBIAN
|-data
  |-data
    |-com.termux
      |-files
        |-usr/bin
```

**Comment by JesusChapman** [comment]
To me the package is not defined haci, even it is not generated, it gives me that error of the photo, and if in Android (without root) you can compile it with all termux, there is available the necessary qt5 libraries and some desktop environments to run it

**Comment by ThiBsc** [comment]
what you can try, is to generate a package with `dpkg-deb` by hand to check if it is working.
Recreate the same tree as you can see in my program and you will be able to test it

**Comment by JesusChapman** [comment]
If it works, I use dpkg like this :

dpkg -b folder/ package.deb

No e used dpkg-deb,. I don't know how it works

**Comment by ThiBsc** [comment]
Yes the tree should be something like this:
```txt
packagename
|-DEBIAN
|-usr
  |-bin
```
Then go on the same level as the `packagename` folder and run `dpkg-deb --build packagename packagename_1.0.dev`

**Comment by JesusChapman** [comment]
![Screenshot_20210602-142326](https://user-images.githubusercontent.com/64093255/120540308-26f13580-c3ae-11eb-9060-40f9483b9294.png)

**Comment by ThiBsc** [comment]
Ok, the problem is in the generation with your configuration, I need more time to investigate, I'll keep you in touch when I'll have news

**Comment by JesusChapman** [comment]
Tanks!

**Comment by ThiBsc** [comment]
But just keep in mind, when I develop this program, I never though that someone use it on android device ;) So it is normal that some problems like this appears

**Comment by JesusChapman** [comment]
Well, yes jajjajaja

**Comment by ThiBsc** [comment]
I tried to install termux on a vm with `android 7.1 x86` but i'm not able to install qt5-base, when I run command `pkg install something`

**Comment by JesusChapman** [comment]
You must report the bug and details of the problem to its developers:

https://github.com/termux/x11-packages

There they will help you

**Comment by JesusChapman** [comment]
As you go bro

**Comment by ThiBsc** [comment]
No had the time yet. I have to find a version of android that I can run on VM to reproduce your behavior.

**Comment by ThiBsc** [comment]
Hi, sorry for the delay. I tried to install termux, with success (the play store version is too old, I had to use the F-Droid version). But after installing `x11-repo`, `qt-creator` and `xfce4-desktop`, I am not able to run GUI program (xcb platform...). How have you done it ? With vnc and connect from another computer ? I am able to compile debpac on android but not running it.

**Comment by JesusChapman** [comment]
What error do you get when you run it?

**Comment by Yisus7u7** [comment]
This conversation is already very long, write to me at my telegram : 

`+57 3006748497`
